[package]
name = "git-lfs-synology"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.21"
futures-macro = "0.3.31"
keyring = { version = "3.6.1", features = ["apple-native", "windows-native", "sync-secret-service"] }
rusqlite = "0.32.1"
