FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y libdbus-1-dev \
                        pkg-config \
                        curl

RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN cargo test --verbose
RUN cargo build --verbose --release