FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y libdbus-1-dev \
                        pkg-config \
                        curl

USER ubuntu
ENV HOME="/home/ubuntu"
RUN mkdir -p ${HOME}
WORKDIR ${HOME}

RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
RUN echo ". \"\$HOME/.cargo/env\"" >> ${HOME}/.bashrc

RUN cargo test --verbose
RUN cargo build --verbose --release