FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y libdbus-1-dev \
                        pkg-config \
                        curl

RUN curl https://sh.rustup.rs -sSf | bash -s -- -y

RUN PATH="/root/.cargo/bin:${PATH}" cargo test --verbose
RUN PATH="/root/.cargo/bin:${PATH}" cargo build --verbose --release