name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: |
        cargo build --verbose --release --target=x86_64-unknown-linux-gnu
        cargo build --verbose --release --target=aarch64-unknown-linux-gnu

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: |
        cargo build --verbose --release --target=x86_64-pc-windows-gnu
