name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
    - name: Setup Cargo Config
      run: |
        mkdir -p .cargo
        echo "[target.aarch64-unknown-linux-gnu]" >> ./.cargo/config.toml
        echo 'linker = "aarch64-linux-gnu-gcc"' >> ./.cargo/config.toml
    - name: Install Rust Toolchains
      run: rustup target add x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: |
        cargo build --verbose --release --target=x86_64-unknown-linux-gnu
        cargo build --verbose --release --target=aarch64-unknown-linux-gnu
    - name: ls
      run: |
        find git-lfs-synology -name git-lfs-synology

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust Toolchains
      run: rustup target add x86_64-pc-windows-msvc aarch64-pc-windows-msvc
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: |
        cargo build --verbose --release --target=x86_64-pc-windows-msvc
        cargo build --verbose --release --target=aarch64-pc-windows-msvc
    - name: ls
      run: |
        ls -recurse | ? { $_.name.contains("git-lfs-synology") }

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust Toolchains
      run: rustup target add x86_64-apple-darwin aarch64-apple-darwin
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: |
        cargo build --verbose --release --target=aarch64-apple-darwin
        cargo build --verbose --release --target=x86_64-apple-darwin
    - name: Build Universal
      run: |
        mkdir -p ./target/universal-apple-darwin/release/
        lipo -create -output ./target/universal-apple-darwin/release/git-lfs-synology ./target/x86_64-apple-darwin/release/git-lfs-synology  ./target/aarch64-apple-darwin/release/git-lfs-synology
    - name: Archive macOS x64 Results
      uses: actions/upload-artifact@v4
      with:
        name: git-lfs-synology.osx-x64
        path: ./target/x86_64-apple-darwin/release/git-lfs-synology
    - name: Archive macOS Apple Silicon Results
      uses: actions/upload-artifact@v4
      with:
        name: git-lfs-synology.osx-x64
        path: ./target/aarch64-apple-darwin/release/git-lfs-synology
    - name: Archive macOS Universal Results
      uses: actions/upload-artifact@v4
      with:
        name: git-lfs-synology.osx-x64
        path: ./target/universal-apple-darwin/release/git-lfs-synology
